name: Data Pipeline

on:
  push:
    branches: [main]
  
jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.*"
      
      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

  
